#!/usr/bin/env python3
"""
Reads meowsql plan-diff JSON result files and prints a GitHub-flavoured
Markdown PR comment.  Exits 1 when any regression is found.

Usage:
  python3 scripts/plan_report.py results/q1.json results/q2.json ...
"""
import json, os, sys


def fmt_cost(c):
    if c >= 1_000_000: return f"{c/1_000_000:.1f}M"
    if c >= 1_000:     return f"{c/1_000:.1f}k"
    return f"{c:.1f}"


def change_label(r):
    if r.get("error"): return "error"
    p = r["pct_change"]
    if r["regression"]: return f"❌ +{p:.0f}%"
    if p < -1: return f"✅ {p:.0f}%"
    return "✅ —"


def main():
    paths = sys.argv[1:]
    if not paths:
        sys.exit("Usage: plan_report.py result1.json ...")

    results = [json.load(open(p)) for p in paths]
    regressions = [r for r in results if r.get("regression")]
    lines = ["## 🐾 MeowSQL Plan Check\n"]

    if regressions:
        lines.append(f"> ⚠️ **{len(regressions)} regression(s) detected** — one or more queries "
                     "became significantly more expensive after the migration in this PR.\n")
    else:
        lines.append("> ✅ **No regressions** — EXPLAIN costs are stable across all tracked queries.\n")

    lines += ["| Query | Before | After | Change | Plan (after) |",
              "|-------|--------|-------|--------|--------------|"]

    for r in results:
        name = os.path.basename(r["query_file"])
        if r.get("error"):
            lines.append(f"| `{name}` | — | — | error | {r['error'][:60]} |")
        else:
            lines.append(f"| `{name}` | {fmt_cost(r['before']['cost'])} "
                         f"| {fmt_cost(r['after']['cost'])} "
                         f"| {change_label(r)} | {r['after']['plan_type']} |")

    for r in regressions:
        name = os.path.basename(r["query_file"])
        lines.append(f"\n<details>\n<summary><b>Regression: {name}</b> — "
                     f"cost {fmt_cost(r['before']['cost'])} → {fmt_cost(r['after']['cost'])} "
                     f"(+{r['pct_change']:.0f}%)</summary>\n")
        if r.get("migration_file"):
            lines.append(f"Migration applied (rolled back): `{r['migration_file']}`\n")
        lines.append(f"Before: **{r['before']['plan_type']}** &nbsp;·&nbsp; "
                     f"After: **{r['after']['plan_type']}**\n</details>")

    lines.append("\n---\n_Generated by [meowsql plan-diff](https://github.com/YoungsoonLee/meowsql)_")
    print("\n".join(lines))
    sys.exit(1 if regressions else 0)


if __name__ == "__main__":
    main()
