import * as vscode from "vscode";
import { AnalyzeResult } from "./runner";

export class ResultPanel {
  private static _instance: ResultPanel | undefined;
  private readonly _panel: vscode.WebviewPanel;

  private constructor(
    private readonly _context: vscode.ExtensionContext,
    panel: vscode.WebviewPanel
  ) {
    this._panel = panel;
    this._panel.onDidDispose(() => {
      ResultPanel._instance = undefined;
    });
  }

  static create(context: vscode.ExtensionContext): ResultPanel {
    if (ResultPanel._instance) {
      ResultPanel._instance._panel.reveal(vscode.ViewColumn.Beside);
      return ResultPanel._instance;
    }
    const panel = vscode.window.createWebviewPanel(
      "meowsqlResult",
      "MeowSQL",
      vscode.ViewColumn.Beside,
      { enableScripts: false, retainContextWhenHidden: true }
    );
    ResultPanel._instance = new ResultPanel(context, panel);
    return ResultPanel._instance;
  }

  showLoading(sql: string) {
    this._panel.title = "MeowSQL — analyzing…";
    this._panel.webview.html = loadingHtml(sql);
  }

  showResult(sql: string, result: AnalyzeResult) {
    this._panel.title = "MeowSQL";
    this._panel.webview.html = resultHtml(sql, result);
  }

  showError(message: string) {
    this._panel.title = "MeowSQL — error";
    this._panel.webview.html = errorHtml(message);
  }
}

function escape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const CSS = `
  body { font-family: var(--vscode-editor-font-family, monospace); font-size: 13px;
         color: var(--vscode-editor-foreground); background: var(--vscode-editor-background);
         padding: 16px 24px; max-width: 860px; }
  h2 { color: var(--vscode-textLink-foreground); margin-top: 24px; margin-bottom: 4px; }
  pre { background: var(--vscode-textBlockQuote-background, #1e1e1e);
        border-left: 3px solid var(--vscode-textLink-foreground);
        padding: 10px 14px; border-radius: 4px; overflow-x: auto;
        white-space: pre-wrap; word-break: break-word; }
  ul { margin: 4px 0; padding-left: 20px; }
  li { margin-bottom: 4px; }
  .tag { display: inline-block; border-radius: 3px; padding: 1px 6px; font-size: 11px;
         background: var(--vscode-badge-background); color: var(--vscode-badge-foreground); }
  .muted { color: var(--vscode-descriptionForeground); font-size: 11px; }
  .warn { color: var(--vscode-editorWarning-foreground); }
  .spinner { font-size: 11px; color: var(--vscode-descriptionForeground); }
`;

function loadingHtml(sql: string): string {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8">
<style>${CSS}</style></head><body>
<p class="spinner">🐾 MeowSQL is analyzing your query…</p>
<h2>Query</h2><pre>${escape(sql)}</pre>
</body></html>`;
}

function resultHtml(sql: string, r: AnalyzeResult): string {
  const roots = (r.root_causes ?? [])
    .map((c) => `<li>${escape(c)}</li>`)
    .join("");
  const warnings = (r.warnings ?? [])
    .map((w) => `<li class="warn">${escape(w)}</li>`)
    .join("");

  const indexSection = r.index_ddl
    ? `<h2>Suggested Index</h2><pre>${escape(r.index_ddl)}</pre>`
    : "";

  const rewriteSection = r.rewritten_query
    ? `<h2>Rewritten Query</h2><pre>${escape(r.rewritten_query)}</pre>`
    : "";

  const warnSection = warnings
    ? `<h2>Warnings</h2><ul>${warnings}</ul>`
    : "";

  return `<!DOCTYPE html><html><head><meta charset="UTF-8">
<style>${CSS}</style></head><body>
<h2>Diagnosis</h2>
<p>${escape(r.diagnosis ?? "")}</p>
${roots ? `<h2>Root Causes</h2><ul>${roots}</ul>` : ""}
${indexSection}
${rewriteSection}
${r.estimated_improvement
    ? `<h2>Estimated Impact</h2><p class="tag">${escape(r.estimated_improvement)}</p>`
    : ""}
${warnSection}
<h2>Original Query</h2><pre>${escape(sql)}</pre>
<p class="muted">Generated by <a href="https://github.com/YoungsoonLee/meowsql">MeowSQL</a></p>
</body></html>`;
}

function errorHtml(message: string): string {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8">
<style>${CSS}</style></head><body>
<h2>Error</h2>
<pre class="warn">${escape(message)}</pre>
</body></html>`;
}
